### ISSUE TITLE
impress.js

### ISSUE THREAD

**Issue by bartaz** [rails-girls-summer-of-code/projects#13]
**Name and Contact of the Project Mentor**
Bartek Szopka @bartaz (bartek.szopka@gmail.com)

**Name of the Project**
impress.js

**URL**
Demo: http://bartaz.github.io/impress.js
Repo: [bartaz/impress.js](http://github.com/bartaz/impress.js)

**About the Project**

Impress.js is a small JavaScript tool for building 3D presentations running in the browser. It uses CSS 3D transforms and transitions.

It already has main set of features that were developed initially, but I stopped developing it while ago. 

Because I still see some interest in the project, especially with people new to web technologies, I'd like to revive the project, fix some issues, add new features, make it more beginner friendly and hopefully find at least small team or community to develop it further. I hope that RGSoC could be a good first step to achieve this goal.

**Technologies**

JavaScript, CSS, HTML

**Suitable for beginners?**

Yes (and no).

**No** 'cause some more exiting tasks (such as extending API) would require some programming skills, especially that JavaScript in browsers is quite tricky environment to start your programming adventure with.

But **yes**, 'cause on the other hand we can for sure find easier tasks to start with. Especially that one of my goals would be to make using impress.js more beginner friendly.

**What are issues/features students may work on?**
- Features and improvements such as: adding substeps, additional configuration options, etc.
- Extending API to make it more flexible.
- Testing impress.js in new browsers (including mobile).
- Improving documentation or demos to make it easier to start for newcomers.
- ... Anything else students will think about that can make project better.

**Comment by lislis** [comment]
awesome!!

**Comment by carmenmitru** [comment]
Hi,

How can I apply for this project?

Thank you!

Carmen

**Comment by bartaz** [comment]
I think all the information needed is here: http://railsgirlssummerofcode.org/students/application/

**Comment by alicetragedy** [comment]
Hi @carmen97 :) yes, just like @bartaz said, read over the information about the student application to see how to apply. We've also written a blog post with a "check list" for everything you need to have for the application: http://railsgirlssummerofcode.org/blog/2015-applications-open/
If you have any specific questions about the project itself, you can contact @bartaz, I'm sure he'll be able to help you out. When you fill out the application, you can add the project name and link there! :)
Otherwise: we suggest going over the project issues outlined above with your coach(es) to define your project plan for the summer. Hope that helped!
