### ISSUE TITLE
Discourse: Advertising Plugin

### ISSUE THREAD

**Issue by eviltrout** [rails-girls-summer-of-code/projects#28]
Name and Contact of the Project Mentor: Robin Ward, robin dot ward at google's email thingy.

Name of the Project: Discourse

URL: http://discourse.org

About the Project: Discourse is modern open source forum software, built in Rails with an Ember.js front end. 

Suitable for beginners? It will be a bit of a challenge but I am prepared to mentor as much as possible to help them get it done!

What are issues/features students may work on? This project is to create a plugin that would allow discourse users to add advertising to their site. This is something that many users would like to help cover the costs of their forum but is not provided by Discourse core.

**Comment by ladydanger** [comment]
:two_women_holding_hands: Me and my pair, @snjqi188, would love to work on this!

**Comment by alicetragedy** [comment]
Hi @eviltrout, glad to see this submission! :+1: 
do you think you could add some extra information about the advertising plugin feature, so that the applicants know what to expect? If possible adding what kind of knowledge is required as a beginner if you expect it to be challenging for them, and maybe a possible roadmap for the summer. It doesn't have to be super detailed, but breaking down the concept of the plugin into chunks for the students would be great. 
thanks in advance!

**Comment by eviltrout** [comment]
Sure!

Knowledge Required:

Javascript: This plugin will be heavy on the Javascript side and lighter on the Ruby side. We hope that our students can freshen up on the Javascript fundamentals before getting started. Going through the basics of Ember.js will also be helpful but I think we can learn enough to get through that if the Javascript basics are solid.

Loose Roadmap:

Week 1 - Set up Discourse development environment
Week 2 - Create basic "hello world" Discourse plugin
Week 3 - Create Ad plugin: first step, shows boxes where ads should be on Discourse
Week 4 - Separate boxes into an Ember component for re-use
Week 5 - Add support for an ad provider to the component (Google? whoever is most popular!)
Week 6 - Add site settings to configure plugin
Week 7 - Create tests for plugin component
Week 8 - Package plugin for Distribution

I am actually not sure if there are more weeks available, but if so we could:
- Give the students extra time to catch up in case any tasks are too difficult
- Support for more Ad providers

**Comment by alicetragedy** [comment]
great @eviltrout, that sounds like a very solid foundation for the applicants, thank you for the thorough description. We're super happy to accept this as a project! Congrats! :tada: 

### Note to Students

please also read the above description and loose roadmap in the comments :)

**Comment by cyberkoi** [comment]
yay, thanks all!

**Comment by mimimalizam** [comment]
Hello @eviltrout! We, me and @Anjazk, are interested to apply for SoC with your project. Even if it seems harder than we expected we are encouraged to contact you because it is stated in project description that you are willing to mentor as much as needed, and we would really like to learn as much as possible. We have our coaches, and also, we have sent you an email. Hope to hear from you soon :)

**Comment by eviltrout** [comment]
Hi all interested parties! Unfortunately we already have a team that is confirmed for this work. Thanks for your interest though!
