### ISSUE TITLE
LEAP Encryption Access Project - Webapp

### ISSUE THREAD

**Issue by varac** [rails-girls-summer-of-code/projects#34]
# Name and Contact of the Project Mentor:

Christoph Klünter, [Pixelated Project](https://pixelated-project.org/) 
# Name of the Project:

[LEAP Encryption Access Project](https://leap.se/) - Webapp
# URL:

https://github.com/leapcode/leap_web/
# About the Project:

LEAP is a dedicated to giving all internet users access to secure communications. Our focus is on adapting encryption technology to make it easy to use and widely available. Like free speech, the right to whisper is a necessary precondition for a free society. Without it, civil society and political freedom become impossible. As the importance of digital communication for civic participation increases, so does the importance of the ability to digitally whisper. LEAP is devoted to making the ability to whisper available to all internet users.

The LEAP Web App provides the following functions:
- User registration and management
- Help tickets
- Client X.509 certificate renewal
- REST API for Secure Remote Password authentication and user creation.
- Webfinger access to user’s public keys
- Email aliases and forwarding
- Localized and Customizable documentation

Written in: Ruby, Rails.
# Suitable for beginners?

Yes, most features are easy to implement, even though you need a (local) running LEAP provider for developing. But we can help how to set one up. 
The one unusual thing is that we use CouchRest::Model instead of ActiveRecord for the database.
# What are issues/features students may work on ?
- Add support for newsletter / announcements to users.
- Add support for quota.
- Add support for token-based user registration.
- Add support for bitcoin payments to the billing module.
- Add support to email ticket issue system for sending and receiving email.

see https://leap.se/en/docs/get-involved/project-ideas#leap-webapp for more details

**Comment by carpodaster** [comment]
Hey @varac,

Thank you for your project proposal!

I have to admit that while I've heard of the pixelated-project.org before, I am not familiar with how it works. Is it a commercial product? (I couldn't find a price tag, just a demo login). Could you briefly illustrate in what way the LEAP project is affiliated with Pixelated?

Quota-support and bitcoin payments also hint at a commercial use (which is not at all bad). Could you outline the use-case for this feature?

**Comment by kaeff** [comment]
I'm not a part of LEAP, but maybe I can try to tackle that question.

LEAP is a software distribution intended for access provider organizations. It's goal is decentralization, i.e. allowing many organisations to provide communication service, nut just google, yahoo and microsoft. Since LEAP is free software, it does not forbid the access provider using it to make money.

Pixelated is a AGPL-licensed software distribution for secure email. It uses LEAP as a provider component, and contains other components like a user agent (e-mail web client). See [this diagram](https://pixelated-project.org/#high-level-overview). Like LEAP, Pixelated is not a commercial service.

My employer, ThoughtWorks, is a development partner of the NGO under whose umbrella this project is developed. ThoughtWorks does not receive money to work on Pixelated or LEAP.

**Comment by varac** [comment]
Hi @carpodaster, 

i'd like to add to what @kaeff already pointed out:

Both Pixelated and LEAP are 100% free and open source projects. 

Pixelated uses LEAP as foundation to base on, but develops a dedicated mail client that integrates with LEAP (while LEAP is offering a desktop client that you need to connect your mail user agent to).

Both projects consider themselves as non-profit, non-commercial. However, besides developing software for end-users, both projects also aim at service providers using the LEAP Platform to offer encrypted services (VPN and Email at the moment for LEAP, Email for Pixelated) to their user base (community or commercial use). To ease the usage of the LEAP Platform as a service provider, we want to include features like bitcoin payment and quota support.

LEAP funding details can be found here:  https://leap.se/en/about-us/partners
Pixelated is funded by Thoughtworks at this moment, who will also contribute with mentoring and coaching.

Cheers, Varac

**Comment by carpodaster** [comment]
Thank you very much for taking the time to clarify, @kaeff and @varac. Accepted! :confetti_ball:

**Comment by varac** [comment]
\o/

**Comment by Karla-Isabel-Sandoval** [comment]
Christoph,

My Rails Girls Summer of Code partner, Emma Koszinowski and I are very interested in the Leap Encryption project because it is written in Ruby and Rails. We are also very interested in working on the issues you mentioned-especially internet users access to secure communications and adding support for newsletters, quotas and payment with bitcoin payments.

We would love to have you as our project mentor. In addition the Leap Encryption project would compliment our  (hopefully) future co-working space at Lookout here if San Francisco, which is perfect because they are also an encryption based company. Please let us know the best way to reach you and wether you would be open to Skyping or google chatting tomorrow.

Cheers,

Karla

**Comment by alicetragedy** [comment]
Hi @varac, I'd like to send you important information regarding the next steps for you as a possible mentor – could you either post your email address here, or shoot us a mail? The address is on the main Rails Girls Summer of Code website (http://railsgirlssummerofcode.org) under "get in touch". Thanks in advance! :tada:

**Comment by varac** [comment]
@alicetragedy i sent you my contact via mail

**Comment by alicetragedy** [comment]
@varac I was just prepping the email for both of you, and it should now be in your inbox. :+1:
