### ISSUE TITLE
At a happy place

### ISSUE THREAD

**Issue by rishijain** [rails-girls-summer-of-code/projects#9]
**Name and Contact of the project Mentor** : Rishi Jain (rishi@joshsoftware.com), Yogesh Khater(yogesh@joshsoftware.com)

**Name of the project** : At a happy place

**URL** : github: rishijain/oneplaceaday   ,  www.athappyplace.com

**About the project**:  The idea is to share that happy place of yours where you recently travelled or found out by sheer luck. Currently user can register, login, add a post (description and photo mainly), add comments.

**Suitable for beginners**: Yes. Both beginners and more experienced developers can contribute.

**What are the issues/features students may work on?:**
1. Integrating social media login and publishing to Facebook and Twitter.
2. Adding ability to search content based on authors, places, content (at the moment ElasticSearch is in our mind).
3. Adding newsletters, subscriptions, notifications for comments.
4. Documentation and test cases.

**Comment by lislis** [comment]
Hey @rishijain! Thanks for proposing your project! Just one thing: The project repository does not display any license. Every project needs to run with a open source license in order to be accepted. Did you maybe forget to put one in the repository? Here is a link to help choose a open source license http://choosealicense.com/

**Comment by rishijain** [comment]
@lislis Thanks for pointing out. Added the license.

**Comment by alicetragedy** [comment]
Hi @rishijain! Thank you for submitting the project and adding the license. 
We usually expect the submitted projects, as stated in our guides, to be a bit more established; not for reasons of prestige, but simply because we think it will be easier for the students to contribute to a project with a bigger 'community'. We did however like your project, as we believe the issues are very beginner-friendly, which is why we'd like to accept it for this year's Rails Girls Summer of Code! Welcome :)

### A note to students

This is a very young project with a lot of good issues that are beginner-friendly. However it is not as established as we would like and thus may not have the highest ranking in the application compared to others with a more established structure and community.

**Comment by rishijain** [comment]
@alicetragedy First of all thank you for accepting it :heart: 
Yes, I totally understand that the project is at very young stage and the issues are beginner friendly. Also, looking at some of the other projects like Bundler, ruby documentation, I knew it will be difficult to get in.
But I am glad that it has been accepted and we look forward to be part of RailsGirlsSummerOfCode.
:+1:

**Comment by anikalindtner** [comment]
:sun_with_face:

**Comment by cheatiiit** [comment]
Hey @rishijain the project sounds amazing. I am looking forward to work on it. Do you people have an IRC channel for discussion.

**Comment by rishijain** [comment]
Hi @cheatiiit , thats awesome. 
Though we do not have an IRC channel, you can contact us at our email address.

**Comment by TanSA05** [comment]
Hey,I was going to apply for RGSoC, and was wondering if you'd be interested in mentoring me and my partner for a project?

**Comment by alicetragedy** [comment]
hi @TanSA05, just to make it clear – @rishijain could be your project mentor if you choose "At a Happy Place" as a project, but you still need local coaches that can help you daily. Just thought I would clarify just in case :)

**Comment by TanSA05** [comment]
Hey, @alicetragedy, I forgot to edit the "a project" to "this project" in my comment. Sorry for that and thanks for the clarification :)

**Comment by rishijain** [comment]
Hi @TanSA05 , thanks for your interest. Please shoot me an email at rishi@joshsoftware.com and let me know your skill level.. basically how comfortable are you with ruby and rails in general.

Thanks @alicetragedy for clearing the confusion.

**Comment by sandrely2611-zz** [comment]
Hi @rishijain! my pair @karenVentura and I are interested in working with you. We're based in Mexico. Still accepting students? We already have our coaches. We'll send you an email :)

**Comment by kinjalgada** [comment]
Hi @rishijain! Your project looks interesting and something new, I and my pair @AniShah are interested in working with you. Are you'll still accepting students? We're based in Mumbai. We already have our coach based in Mumbai as well. We'll send you an email :)

**Comment by alicetragedy** [comment]
We're sorry @kinjalgada and @AniShah, applications for RGSoC closed 7 hours ago (April 14th, 23:59 UTC) so it's not possible to submit an application anymore. You can always give it a try next year! :tada:
